/**
 * AffectJS DSL Parser and Compiler
 *
 * Main entry point for the @affectjs/dsl package
 */

import { readFileSync } from "fs";
// Parser will be generated by Peggy during build
// @ts-ignore - Generated file
import { parse } from "./parser";
import {
    compileToOperations,
    type CompiledOperations,
    type CompileToOperationsOptions,
    type Program,
    type AffectBlock,
    type ConvertBlock,
    type ASTNode,
} from "./compiler-to-operations";

/**
 * Parse DSL file and return AST
 */
export function parseDsl(
    dslContent: string
): Program | ConvertBlock | AffectBlock {
    try {
        const ast = parse(dslContent) as Program | ConvertBlock | AffectBlock;
        return ast;
    } catch (error) {
        throw new Error(`DSL parsing failed: ${(error as Error).message}`);
    }
}

/**
 * Parse DSL file from path
 */
export function parseDslFile(
    filePath: string
): Program | ConvertBlock | AffectBlock {
    const content = readFileSync(filePath, "utf-8");
    return parseDsl(content);
}

/**
 * Compile DSL to Operation[] objects
 */
export function compileDsl(
    dslContent: string,
    options?: CompileToOperationsOptions
): CompiledOperations {
    const ast = parseDsl(dslContent);
    return compileToOperations(ast as Program | ConvertBlock | AffectBlock, options);
}

/**
 * Compile DSL file to Operation[] objects
 */
export function compileDslFile(
    dslPath: string,
    options?: CompileToOperationsOptions
): CompiledOperations {
    const content = readFileSync(dslPath, "utf-8");
    return compileDsl(content, options);
}

export type {
    Program,
    ConvertBlock,
    AffectBlock,
    ASTNode,
    CompiledOperations,
    CompileToOperationsOptions,
} from "./compiler-to-operations";
