/**
 * AffectJS DSL Parser and Compiler
 *
 * Main entry point for the @affectjs/dsl package
 */

import { readFileSync } from "fs";
// Parser will be generated by Peggy during build
// @ts-ignore - Generated file
import { parse } from "./parser";
import {
    compileToJs,
    type Program,
    type CompileOptions,
    AffectBlock,
    ConvertBlock,
} from "./compiler";

/**
 * Parse DSL file and return AST
 */
export function parseDsl(
    dslContent: string
): Program | ConvertBlock | AffectBlock {
    try {
        const ast = parse(dslContent) as Program | ConvertBlock | AffectBlock;
        return ast;
    } catch (error) {
        throw new Error(`DSL parsing failed: ${(error as Error).message}`);
    }
}

/**
 * Parse DSL file from path
 */
export function parseDslFile(
    filePath: string
): Program | ConvertBlock | AffectBlock {
    const content = readFileSync(filePath, "utf-8");
    return parseDsl(content);
}

/**
 * Compile DSL to JavaScript code
 */
export function compileDsl(
    dslContent: string,
    options?: CompileOptions
): string {
    const ast = parseDsl(dslContent);
    return compileToJs(ast as Program | ConvertBlock | AffectBlock, options);
}

/**
 * Compile DSL file to JavaScript
 */
export function compileDslFile(
    dslPath: string,
    options?: CompileOptions
): string {
    const content = readFileSync(dslPath, "utf-8");
    return compileDsl(content, options);
}

export {
    compileToJs,
    type Program,
    type ConvertBlock,
    type AffectBlock,
    type ASTNode,
    type CompileOptions,
} from "./compiler.js";
